dist: xenial
os: linux
language: java
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - development
install: ''
services:
- docker
before_install:
- docker version
jobs:
  fast_finish: true
  include:
  - jdk: openjdk11
    env:
    - DESC="build with OPENJDK11"
    - USE_MAVEN_REPO="true"
    - CMD="mvn clean package"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: QLCYkoEw7uR9NsR7SBDFlKiAIw2zG9++peNO6Der6skdIticP8MlZhIzF5hbwcz3trM5ikEQctWk6E5YMsfiXkMuwYcoTIRg5pv8VQPA/XT4fBFL9WGh0cYIXWNkPfrY3fjwesg9KFsOek17OFa13PfeTUJf449AID72rtRx0TfdRCyjwiwPFjSoq5sJmJPC509TwRrRfYiUmsuox5LUVvy1HRk+ycwlwGoiVfciW2xUc0tw82YLv834WvXa/Qf8QWUeC5Aiz6YhnssBzw+0/5810ojJNxZEExxPJR+utrlZ8M56VdOKHf2Dxa30ZPxEhAAvf1z9VWiU9h0wYYnVMtlusW8RCHWcy+hM4q7yA9e+ovMjydHIaFfqAAmX5dHopMjjL9wscVOmO/HrWe12IYBe3gBRF7Q6wzPHw7nNp5MDhuqUmOdd2Dx5B63+tiT/KPPjDeJzY+h2T93tDSj9lJgb4sT2m9r0eOfEsWiv7adBWi0OoM3SR7yCxsZYJkaag93SqQxZxjz/+PBXjscPB5ENvR0ftpYTJ8PUsLUl56A5YCXgoxoijFNo1D8Nf12MDoAgWE5X7t3+ZMpH02g38GKS1EDM+dm1G9ZZ62IEGSERW6+SGqcHknT/+LRAKE+bxrY7CIGIpEWb2/5dcjGi2Zaysk9wDlq0v7jWeF8JnzI=
  - secure: WnwOnLLsWHKOEPjqO3ZbvsAOcRaxnWOV3AIEd4wih/bwJVDUGLYzN2UPoUdes7tKpS1oPoORoiUvmq3mDv7W480RSWSLAl/Ey3ZRQUJPO2sI4r94uRKrL2GNQMOpVitnjOYc1BtYi3hIc5iOqtUvXy01dHffcxvEcRr+wgVpKijsS9OKYS1EWgOae3XktQflWJ3jCyaxiN0drP+DMQQhjZ26JgfySmGgh1mWgSl4Cx6706iDHkamTP/kmsSEKfuiLbvO/+XVWWBMeHrUEk2rzdFYUzVx87grkT/GF48zGTixX0S7KruG/rQqK4s59nefetEa87RpRKYqcsVZOaTmgjPS6jhoGh0C1D/HtnULiQT8WvrLSJoD5vUDyaLnx5RE0psNp/tnHMnWzM+jxTEu7VUaRw1l0pn5gH5Q3q7v06Fzal1rjDM2RUxjqRyfiEULiIBcE0HQ11rV890JmrYtRVlBgheJy4V4UXNsPXFTrMrWIJqW1zKD4pAjFUdP6/rUNDa0LTrHOtdTjKfd3NyUAKUMXIc9awDBuVwFFfwLDjdJa83w6Nh3Joc847+tAJeOCSrcPjKLvk4JXwe7Srjlzchrk4G9KAti3tcb0VGzx2UvgBFdnIrboJHohSAF2IC03H0FW5t7vwesq+PX4xg1srPFS+Y3P/6SSxXaObzKIAg=
script:
- "mvn -f ./fileconsumer clean package -B"
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "development" ]; then echo "latest"; else echo
  $TRAVIS_BRANCH ; fi`
- export IMAGE_NAME=sombose/file-consumer
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
